openapi: 3.1.0
info:
  title: Mind Map Viewer API
  version: 1.0.0

servers:
  - url: https://mindmap-viewer.onrender.com

paths:
  /generate:
    post:
      operationId: generateMindMapViewer
      summary: Generates a public mind map viewer from MindElixir JSON
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                mindmap:
                  type: object
                  properties:
                    nodeData:
                      type: object
                      properties:
                        id:
                          type: string
                        topic:
                          type: string
                        root:
                          type: boolean
                        children:
                          type: array
                          items:
                            type: object
                            properties:
                              topic:
                                type: string
                              children:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    topic:
                                      type: string
                                  required:
                                    - topic
                            required:
                              - topic
                      required:
                        - id
                        - topic
                        - root
              required:
                - title
                - mindmap
      responses:
        '200':
          description: Generates a visual HTML mind map from an OPML file and returns a direct, public URL to the viewer file hosted at /static/{filename}.
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    format: uri
                    description: The full public URL to the generated mind map viewer HTML file
                required:
                  - url
